# Generated by Django 4.2.1 on 2023-05-04 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "author",
                    models.CharField(
                        blank=True, default="James Hamisi", max_length=100, null=True
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "author_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("awareness", "Awareness"),
                            ("technology", "Technology"),
                            ("health", "Health"),
                            ("social", "Social"),
                            ("communication", "Communication"),
                            ("sanity", "Sanity"),
                        ],
                        default="awareness",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
