# Generated by Django 4.2.1 on 2023-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(
                blank=True, default="Kemboi Duncan", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.CharField(
                choices=[
                    ("art", "Art"),
                    ("technology", "Technology"),
                    ("music", "Music"),
                    ("food", "Food"),
                ],
                max_length=20,
            ),
        ),
    ]
